services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs #maps log file
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/weatherapp
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@weather.com
      PGADMIN_DEFAULT_PASSWORD: weather123
    depends_on:
      - db

volumes:
  pgdata:
  
